# @package _global_

distributed:
  infer_device: "cpu"
  host: ""
training:
  num_workers: 8
  num_rollouts: 48
  steps_per_epoch: 1000
agent:
  learning_starts: 100
task:
  env_id: "InvertedDoublePendulum-v4"

