defaults:
  - _self_
  - agent: sac
  - task: mujoco
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

distributed:
  server_addr: "127.0.0.1"
  master_port: { env: MASTER_PORT, default: 4444}
  m_server_name: "m_server"
  m_port: ${distributed.master_port}1
  m_server_addr: ${distributed.server_addr}:${distributed.m_port}

  r_server_name: "r_server"
  r_port: ${distributed.master_port}2
  r_server_addr: ${distributed.server_addr}:${distributed.r_port}

  c_server_name: "c_server"
  c_port: ${distributed.master_port}3
  c_server_addr: ${distributed.server_addr}:${distributed.c_port}

  train_device: "cuda:0"
  infer_device: "cuda:0"
  host: ""


evaluation:
  num_workers: 2
  num_rollouts: 4
  seed: 456
  deterministic_policy: true
  num_episodes: 2

training:
  num_workers: 4
  num_rollouts: 8
  seed: 123
  num_epochs: 1000
  steps_per_epoch: 5000
  prefetch: 5

